# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - Seat-Reservation-System-BE

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Explicitly specifying Node.js version 20

      - name: Install dependencies
        run: npm install  # Install dependencies

      - name: Build the application
        run: npm run build --if-present  # Build the application

      - name: Run tests
        run: npm run test --if-present  # Run tests if applicable

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: .  # Path where your application files are located

  deploy:
    runs-on: windows-latest  # Use Windows for deployment
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Seat-Reservation-System-BE'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F0EB328364014DB896F5EF8E0DB69D76 }}
          package: '.'  # Ensure this points to the correct path of your built application
