name: Build and deploy Node.js app to Azure Web App - Back-End-1

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  # Ensure this matches your local Node.js version

      - name: Install dependencies
        run: |
          cd backend  # Navigate into the backend directory
          npm install

      - name: Run build (if applicable)
        run: |
          cd backend
          npm run build --if-present  # Only if you have a build step defined

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: backend  # Make sure this points to the backend directory

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: List downloaded files
        run: |
          ls -R  # List all files to verify they are downloaded correctly
          # Check specifically in the backend folder
          ls -R backend 

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'Back-End-1'  # Ensure this matches your Azure Web App name
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_26C091E8DFFD43A288BA0E58A6D55AE5 }}
          package: './backend'  # Path to the backend directory
