name: Deploy Node.js app to Azure Web App - Back-End-1

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  # Ensure this matches your local Node.js version

      - name: Install dependencies
        run: |
          cd backend  # Navigate into the backend directory
          npm install

      - name: List files before deployment
        run: |
          cd backend
          ls -R  # List all files to verify they are present

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'Back-End-1'  # Ensure this matches your Azure Web App name
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_26C091E8DFFD43A288BA0E58A6D55AE5 }}
          package: './backend'  # Path to the backend directory
